### ISSUE TITLE
How to upload offline images using queue

### ISSUE THREAD

**Issue by xinhash** [billmalarky/react-native-queue#20]
Hi, Thanks for this wonderful plugin. Although I've hit a roadblock ( may not be plugin issue)

I wanted to push clicked Images to queue and upload these when connected to internet.
```jsx
async init() {
    const queue = await queueFactory();
    queue.addWorker(
      "update-db",
      async (id, payload) => {
        const {key, formData } = payload;
        const response = await uploadImage(formData, false);
        if (response && response.done && response.formObj) {
          const { done, formObj } = response;
          await Database.updateUnloadingForm(key, formObj);
        }
      },
      {
        onStart: async (id, payload) => {
          console.log(
            'Job "update-unloading-supervisor-form" with id ' +
              id +
              " has started processing."
          );
        },
        onFailed: async (id, payload) => {
          console.log('Job "job-name-here" with id ' + id + " has failed.");
        }
      }
    );

    queue.start();

    this.setState({
      queue
    });
  }
```
and the Upload Image is a function which basically returns 
```
import { RNS3 } from "react-native-aws3";
return RNS3.put(file, options);
```
Upon logging this I get following error:
```
{ status: 0,
05-03 17:28:14.222 21494 21543 I ReactNativeJS:   text: 'Unable to resolve host "bucketName.s3.amazonaws.com":No address associated with hostname',
05-03 17:28:14.222 21494 21543 I ReactNativeJS:   headers: {} }
```
I want to know how does a worker know that job has been completed. Basically if I am able to do the same on image upload error, my jobs will be retried

**Comment by xinhash** [comment]
I made some changes and now the Job is failing when unable to upload Image. If I want the job to stay alive and retry. Please suggest me the same. Also is there any way to access failed jobs ( or are they flushed out from the queue upon failure ).

**Comment by billmalarky** [comment]
There is currently no way to retry jobs that have failed completely. The best way is to use the "onFailed" job lifecycle callback to simply create a new job. If your jobs are failing that much though you probably have a more fundamental issue.

Thank you for the compliment on the plugin :-)
