### ISSUE TITLE
Can i change the scheduled time from 15 minutes to 5 minutes?

### ISSUE THREAD

**Issue by roysG** [billmalarky/react-native-queue#27]

**Comment by billmalarky** [comment]
If you are referring to the background task schedule, the minimum time for cross platform background jobs is 15 minutes. This limit is based on an iOS constraint.

**Comment by roysG** [comment]
So just to be sure i understand,
For example if app is in background and i need to update some action to the specific waiting user, i may update hie after 15 minutes and no immediately, right?

**Comment by billmalarky** [comment]
Background jobs run approximately every 15 minutes. It isn't exact.
