### ISSUE TITLE
Schedule local notification by calling API every interval

### ISSUE THREAD

**Issue by gonglowbat** [billmalarky/react-native-queue#28]
I saw the example in conjunction with https://github.com/jamesisaac/react-native-background-task.

I would like to implement something I call fake remote push notification. Instead of using real remote push notification, I would like to running a background task every midnight to fetch to some API which return some information to be use in making a local notification. Then, after successfully receive the information, I will schedule local notification using https://github.com/zo0r/react-native-push-notification.

Is it seems possible?

**Comment by billmalarky** [comment]
Yes this is absolutely possible so long as it doesn't have to fire at
exactly midnight.

Background tasks can be scheduled as often as every ~15min but they don't
fire exactly on schedule they are approximate.

So just set up a background task that checks if it's after midnight then
fire the API request for the day.

**Comment by gonglowbat** [comment]
I did some experiments to prove the concept but I still cannot get the example to successfully runs.

I found that iOS background task will not run if the app is manually closed.

- https://developer.apple.com/library/archive/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW7

- https://github.com/jamesisaac/react-native-background-task#limitations

But how the iOS alarm in clock app be able to run even though the app is manually close?

Sorry for off topic question.

**Comment by billmalarky** [comment]
Background tasks require the app to be running. There is no way to get
around that currently and no way to startup app programmatically.

The apps that ship with the OS have access to functionality and permissions
that 3rd party developers do not.

**Comment by gonglowbat** [comment]
Thanks for clarification.

As @billmalarky said, background tasks require app to be running. So, in my case, this is not possible and should use remote push notification.

I close this issue.

**Comment by billmalarky** [comment]
You are correct. It appears remote push notification is the solution for
your use case.
--------------------------------------------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es
