### ISSUE TITLE
How to flush the jobs from the queue or check the status of the queue

### ISSUE THREAD

**Issue by patrickCode** [billmalarky/react-native-queue#35]
I am using the queue to create some jobs that will be triggered in the background. However, I have a situation where I need to flush all the jobs from the queue (there is some business logic where these jobs become irrelevant in case the user does some action on the UI). How do I flush the jobs from the queue? Is there an API exposed for that?

Also is there a way how I can check the status of the queue (like how many jobs are left in the queue to be processed). 

Also please let me know if ordering is guaranteed in the queue.
If I execute the following code:
`queue.createJob("j1", {}, { timeout: 5000 }, false)`
`queue.createJob("j2", {}, { timeout: 5000 }, false)`
`queue.createJob("j3", {}, { timeout: 5000 }, false)`
Will the jobs be executed in the order j1 -> j2 -> j3 when I do `queue.start(20000)`?

**Comment by The0racle** [comment]
I believe there already is an api for that. Take a look [here](https://github.com/billmalarky/react-native-queue/blob/master/Models/Queue.js#L406-L432)

You can use `queue.flushQueue()` or pass a jobName to cancel only those jobs `queue.flushQueue('jobName')`

**Comment by sutefan1** [comment]
The status of the queue can be checked with [getJobs](https://github.com/billmalarky/react-native-queue/blob/5c45bf92a6c24275feb753cc95366e74c754a956/Models/Queue.js#L210).

**Comment by patrickCode** [comment]
I believe the above APIs will solve my issue. Closing this issue.
