### ISSUE TITLE
what is the difference between worker and job?

### ISSUE THREAD

**Issue by aacxg** [billmalarky/react-native-queue#4]
what is the difference between worker and job?

**Comment by rexxars** [comment]
A worker is the function that handles jobs of a given type.

For example, if you were to make a queue that downloads files, you would have a worker that did the actual HTTP request and stored the file on the device, while jobs contain the details of the download - the URL that should be downloaded, for instance.

**Comment by billmalarky** [comment]
Yep, the "worker" is just a function that is executed every time a "job" is
pulled off the queue and processed.

A simple way to understand it (though not a perfect analogy) is think of
jobs as objects in an array of job objects (the array acting as a simple
"queue" in our basic analogy).

Then if you ran a forEach() on that array of job objects, the worker in
this analogy is the function you pass into forEach() that actually does
something with each job object in the array.

IE: jobs.forEach(worker(job));

Hope this makes sense!
