### ISSUE TITLE
Clarification on Background Tasks

### ISSUE THREAD

**Issue by juddey** [billmalarky/react-native-queue#42]
Hello,

Just looking at your lib for queue and upload of images/videos and have a question about what you said in #29:

> The main thing is remember background tasks are limited to ~30 seconds cross platform so ensure your job can complete in that time frame (or break it up into separate tasks).

Does this mean that the upload would need to complete in this timeframe, or is it just that the job in the queue would need to be kicked off? I'm assuming the former but thought I'd check.

In this case, https://github.com/joltup/react-native-threads might be a better choice to work with your lib.. .as it doesn't seem to have the 30 second restriction?

**Comment by billmalarky** [comment]
Yes any job that is processed in a background task is limited to at most 30
seconds of execution, so the upload would need to complete during that
time. If you can't complete the upload in that time limit you will have to
get creative. For example you can do something like break the upload into
chunks and reassemble on the backend (ie if a large video file takes 2
minutes to upload then break it up into 6 jobs that each upload 1/6 video
in 20 seconds and then stitch back together on backend). Realistically you
prob want to limit the job to 25 seconds and if it times out for some
reason at least you have 5 seconds to handle that error case gracefully -
if you hit the hard OS enforced timeout I don't think your code will get a
chance to handle the timeout gracefully I suspect iOS will just kill the
process.

Note that this is an operating system limitation (specifically iOS if I
recall correctly), it's not a limitation related to react-native-queue
specific code or anything like that.

React-native-queue is agnostic and can integrate with just about anything,
so sure there's no reason to feel limited to the packages that I integrate
with in my examples, they are just there to help people wrap their heads
around how RNQ can be integrated into anything. That said I suspect
react-native-threads will run indefinitely so long as your app is in *focus*,
it may not run at all when your app is not in focus (which is what
the "react-native-background-task" library will do). As such I'm not sure
react-native-threads will accomplish what you need (if what you need truly
is background job processing ie when your app is running but the user isn't
actively interacting with it).

**Comment by juddey** [comment]
Wow! Thanks for the speedy, detailed response. I shall close this out now as you've answered my questions and exceeded my expectations with your answer. :100: :star:

**Comment by billmalarky** [comment]
Haha thank you!
