### ISSUE TITLE
Existing jobs fail if there is a dangling job in the database

### ISSUE THREAD

**Issue by daku** [billmalarky/react-native-queue#7]
Output below. I am not sure how I ended up in this state, but I used to have a `jobPublishLocation` and I don't have it anymore. However, this failure was happening when I was trying to run a different `jobPublishPost`. 

After uninstalling/installing my app the error went away.

```
02-13 13:53:36.555 10746 21171 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
02-13 13:53:36.555 10746 21171 W ReactNativeJS: Error: Job jobPublishLocation does not have a worker assigned to it.
02-13 13:53:36.555 10746 21171 W ReactNativeJS: getConcurrency@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:86548:26
02-13 13:53:36.555 10746 21171 W ReactNativeJS: http://localhost:8081/index.delta?platform=android&dev=true&minify=false:81631:67
02-13 13:53:36.555 10746 21171 W ReactNativeJS: write@[native code]
02-13 13:53:36.555 10746 21171 W ReactNativeJS: getConcurrentJobs$@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:81619:33
02-13 13:53:36.555 10746 21171 W ReactNativeJS: tryCatch@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14069:23
02-13 13:53:36.555 10746 21171 W ReactNativeJS: invoke@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14242:32
02-13 13:53:36.555 10746 21171 W ReactNativeJS: http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14112:30
02-13 13:53:36.555 10746 21171 W ReactNativeJS: tryCatch@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14069:23
02-13 13:53:36.555 10746 21171 W ReactNativeJS: invoke@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14145:30
02-13 13:53:36.555 10746 21171 W ReactNativeJS: http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14173:19
02-13 13:53:36.555 10746 21171 W ReactNativeJS: tryCallTwo@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:13407:9
02-13 13:53:36.555 10746 21171 W ReactNativeJS: doResolve@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:13571:25
02-13 13:53:36.555 10746 21171 W ReactNativeJS: Promise@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:13430:14
02-13 13:53:36.555 10746 21171 W ReactNativeJS: callInvokeWithMethodAndArg@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14172:29
02-13 13:53:36.555 10746 21171 W ReactNativeJS: enqueue@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14177:157
02-13 13:53:36.555 10746 21171 W ReactNativeJS: http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14112:30
02-13 13:53:36.555 10746 21171 W ReactNativeJS: async@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14193:69
02-13 13:53:36.555 10746 21171 W ReactNativeJS: getConcurrentJobs@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:81614:40
02-13 13:53:36.555 10746 21171 W ReactNativeJS: start$@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:81512:71
02-13 13:53:36.555 10746 21171 W ReactNativeJS: tryCatch@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14069:23
02-13 13:53:36.555 10746 21171 W ReactNativeJS: invoke@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14242:32
02-13 13:53:36.555 10746 21171 W ReactNativeJS: http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14112:30
02-13 13:53:36.555 10746 21171 W ReactNativeJS: tryCatch@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14069:23
02-13 13:53:36.555 10746 21171 W ReactNativeJS: invoke@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14145:30
02-13 13:53:36.555 10746 21171 W ReactNativeJS: http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14173:19
02-13 13:53:36.555 10746 21171 W ReactNativeJS: tryCallTwo@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:13407:9
02-13 13:53:36.555 10746 21171 W ReactNativeJS: doResolve@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:13571:25
02-13 13:53:36.555 10746 21171 W ReactNativeJS: Promise@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:13430:14
02-13 13:53:36.555 10746 21171 W ReactNativeJS: callInvokeWithMethodAndArg@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14172:29
02-13 13:53:36.555 10746 21171 W ReactNativeJS: enqueue@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14177:157
02-13 13:53:36.555 10746 21171 W ReactNativeJS: http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14112:30
02-13 13:53:36.555 10746 21171 W ReactNativeJS: async@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:14193:69
02-13 13:53:36.555 10746 21171 W ReactNativeJS: start@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:81478:40
02-13 13:53:36.555 10746 21171 W ReactNativeJS: createJob@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:81468:21
02-13 13:53:36.555 10746 21171 W ReactNativeJS: http://localhost:8081/index.delta?platform=android&dev=true&minify=false:81331:26
02-13 13:53:36.555 10746 21171 W ReactNativeJS: getQueue@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:81311:9
02-13 13:53:36.555 10746 21171 W ReactNativeJS: add@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:81330:17
02-13 13:53:36.555 10746 21171 W ReactNativeJS: startPublishJob@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:70845:44
02-13 13:53:36.555 10746 21171 W ReactNativeJS: touchableHandlePress@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:37523:47
02-13 13:53:36.555 10746 21171 W ReactNativeJS: touchableHandlePress@[native code]
02-13 13:53:36.555 10746 21171 W ReactNativeJS: _performSideEffectsForTransition@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:36807:36
02-13 13:53:36.555 10746 21171 W ReactNativeJS: _performSideEffectsForTransition@[native code]
02-13 13:53:36.555 10746 21171 W ReactNativeJS: _receiveSignal@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:36740:46
02-13 13:53:36.555 10746 21171 W ReactNativeJS: _receiveSignal@[native code]
02-13 13:53:36.555 10746 21171 W ReactNativeJS: touchableHandleResponderRelease@http://localhost:8081/index.delta?platform=android&dev=true&minify=false:36625:26
```

**Comment by billmalarky** [comment]
If you have old jobs you can flush them much easier than doing a full reinstall by simply calling 

```
queue.flushQueue(); // flush all jobs.
```

or in your case,

```
queue.flushQueue('jobPublishLocation'); // only flush jobPublishLocation jobs.
```

Link to code doc: https://github.com/billmalarky/react-native-queue/blob/master/Models/Queue.js#L381

I'm going to close this, as the intended functionality is to throw error and fail if a job is pulled off the queue that has no worker assigned to it. I really don't want this type of thing to silently fail since that opens the door to some pretty critical bugs.

**Comment by daku** [comment]
the issue wasn't that I pulled a job that had no worker assigned, the issue
was that I pulled a job that *had* a worker assigned and still saw the
error for a different job. I agree that the former scenario should not fail
silently, but to crash an app because there is any dangling job in the DB
might be too aggressive in a production environment (when our app gets
there).

**Comment by daku** [comment]
thanks for the debugging tips!

**Comment by billmalarky** [comment]
Hmm, I'm definitely seeing your point. Perhaps it should console.error() instead of throw fatal error.

That way it will redbox in dev environment, which would serve to alert engineering and force them to fix the issue, but silently fail in production.

Or, even better, what are your thoughts on catching all errors that occur in the library, and then emitting them off the queue object? This is what the popular node kue library does. It forces best practices in production (ie doing something with bugs/errors not silently ignoring), but still allows for silent failure in prod.

https://github.com/Automattic/kue#error-handling

**Comment by daku** [comment]
wow, this is a great idea (kue error handling). Especially if I can distinguish between different error types: job failures, db errors, library errors, etc. That way, I can dispatch relevant redux actions to update the UI. I have been thinking about how to notify users if a job failed after all retry attempts, I wonder if this can help address that...

**Comment by billmalarky** [comment]
Just fyi, I looked into this again and with the current logic if a job is pulled off the queue and doesn't have a worker assigned to it it really does break the queue logic so I'm going to keep that fatal thrown error (recall we had discussed using console.error or console.warn to silently error in prod).

>the issue wasn't that I pulled a job that had no worker assigned, the issue
was that I pulled a job that *had* a worker assigned and still saw the
error for a different job.

When you started up the queue it pulled the "next" job off the top (depending on how your ordered it via priority etc), the "next job" at some point was an old job that you no longer were actually using and thus had no worker assigned to it, but it was still in the realm database. This is why flushing the queue resolved the issue entirely.

I've investigated building the queue error event logic, but currently it will provide little value as the only place that throws errors that are uncaught are places where an "error" situation truly is breaking. I think event logic will be valuable at some point in the future but I'm trying to prioritize development and I think what you say next is higher priority:

>I have been thinking about how to notify users if a job failed after all retry attempts, I wonder if this can help address that

^ This seems like functionality that is needed more than the event logic for now.

Seems like the best solution for this type of functionality is allowing an "onFailure" handler function to be supplied as a [worker option](https://github.com/billmalarky/react-native-queue#worker-options). This would be a function that is called with the job id and job data when a job failed after all retry attempts. For that matter, it would probably make sense to have a series of optional lifecycle handlers like "onSuccess", "onFailure", "onComplete" so you can easily hook logic in wherever you want during the job lifecycle. 

I imagine it would look something like this in practice:

```
queue.addWorker('job-name-here', (id, payload) => { console.log(id); }, {
  
  // Set max number of jobs for this worker to process concurrently.
  // Defaults to 1.
  concurrency: 5,

  onSuccess: function(id, payload) {
    console.log('job ' + id + ' finished processing successfully'); // Sure code that you would put here could be simply placed at the end of the standard "worker" handler, but breaking it out into an onSuccess handler is a better place for logic unrelated to the actual job process itself, like code that updates UI by dispatching a redux action or something
  },
  onFailure: function(id, payload) {
    console.log('job ' + id + ' failed'); // Not sure if this should fire with every failed attempt or only if all attempts fail and the failure attempt limit is hit. Maybe it makes sense to have an "onFail" hook that fires on each fail and an "onFinalFailure" or something that fires when the job has failed enough times to reach the max attempts limit.
  },
 onComplete: function(id, payload) {
    console.log('job ' + id + '  complete'); // This fires when a job is marked as complete after it either succeeds or fails enough times to hit max attempts limit. IE this is similar to the [.finally()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally) promise method logic.
  },
  
}); 
```

**Comment by daku** [comment]
Thank you so much for looking into this. `onComplete` sounds like a great
idea, along with the other callbacks. Taking it in the call to `addWorker`
should work very well I think.

- Akshay

**Comment by billmalarky** [comment]
Daku,

Thanks for your feedback.

The job lifecycle callback functionality has now been added via this PR:

https://github.com/billmalarky/react-native-queue/pull/14

Functionality now exists in react-native-queue version 1.2.0, and the new functionality has been published to npm.

For more info on the new functionality, take a look here:

https://github.com/billmalarky/react-native-queue#options-and-job-lifecycle-callbacks

**Comment by daku** [comment]
Thank you, this is great!

**Comment by wkarimvd** [comment]
i have face the same issue and resolved it after spending 3 days hitting my head on the table. There was very silly bug in my worker id. I created workers manually but I create my job dynamically, there was a space in my worker id; which i saved in my local storage. 
Example : 
queue.addWorker("create-user", aync ({ id, payload }) => { //code goes here } ); // it is fine 
problem was here 
this.state.queue.createJob(jobId); // here jobId was culprit because it was coming from other source and had the space in the ending :-(

jobId = 'create-user   '; // it was something like that. So double check your id
